# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
site:
name: NothingMuch
description: 'We help you with transitioning your business online!'
keywords:    "Web development, User Interface, UI, User Experience, UX, UAT, Website, Webpage, Cloud, Tutorials, Scripts, PHP, HTML5, CSS3, Jquery, Frameworks"
logo: "images/logo.png"

title: NothingMuch
email: nomu@yopmail.com
description: We help you to transistion your business online!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nothingmuch.in" # the base hostname & protocol for your site
twitter_username: NoMuInc
github_username:  nomu


### content configuration ###

favicon:     "images/favicon.png"
touch_icon:  "images/favicon.png"
google_analytics_key:  UA-63345215-1

# Build settings
markdown: kramdown
highlighter: false

# Author
author:
    name: 'SantoshJ'
    email: ''
    uri: 'https://github.com/MrBeerBrewer'

